apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: common
  namespace: argo
spec:
  description: Project containing all common resources required to run kubernetes cluster
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
